name: noodle
favicon: null
layout_spectrum: 0.3166967066936195
typography_spectrum: 0.09190181060694158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16554334620013833
  lightness: 0.9855993208475411
  saturation: 0.836426499299705
  rhythmicContrast: 0.2831088996026665
purpose: []
